language: python
sudo: enabled
services:
- mysql
python:
- "3.5"
env:
global:
- TRAVIS=true
# command to install dependenci
install: 
- pip install -r requirements.txt     
script: 
    python main.py test
