language: python
python:  
  - '3.5'
  - '3.6'
before_install: 
  - pip install --upgrade pyflakes
script:
  - pyflakes main.py
branches:
  only:
    - master
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=[access_token]